language: node_js
node_js:
  - "12.13.1"

install:
  - yarn global add lerna jest
  - lerna bootstrap

matrix:
  include:
    - name: couroubledesign Pipeline
      env: PACKAGE_LOCATION=packages/couroubledesign PACKAGE_NAME=cbeyondvr-monorepo  DEPLOY_TO=couroubledesign
    - name: dmgdesign Pipeline
      env: PACKAGE_LOCATION=packages/dmgdesign PACKAGE_NAME=cbeyondvr-monorepo DEPLOY_TO=dmgdesignsf
    - name: villa-clementine Pipeline
      env: PACKAGE_LOCATION=packages/villa-clementine PACKAGE_NAME=cbeyondvr-monorepo  DEPLOY_TO=villa-clementine

cache:
  yarn: true

script:
  - cd packages/ui-kit
  - yarn build
  - cd ../../$PACKAGE_LOCATION
  - yarn build
#  - yarn test

# development flow: deploys on zeit now
deploy:
  provider: script
  script: yarn run now ./$DEPLOY_TO_PREFIX$DEPLOY_TO --prod --token=$NOW_TOKEN
  skip_cleanup: true
  app: $PACKAGE_NAME
  on:
    all_branches: true
branches:
  only:
    - master
