language: node_js
node_js:
  - "12.13.1"

install:
  - yarn global add lerna jest now
  - lerna bootstrap

matrix:
  include:
    - name: villa-clementine Pipeline
      env: PACKAGE_LOCATION=packages/villa-clementine PACKAGE_NAME=cbeyondvr-monorepo DEPLOY_MOVE_TO=.netlify/build

cache:
  yarn: true
  directories:
    - node_modules/
    - $PACKAGE_LOCATION/.cache

before_deploy:
  - cd packages/ui-kit
  - yarn build
  - cd ../../$PACKAGE_LOCATION
  - yarn build

<<<<<<< HEAD
# script: now --token=$NOW_TOKEN --target staging
=======
# development deploys on zeit now
>>>>>>> master
deploy:
  provider: netlify
  site: $NETLIFY_VILLA_CLEMENTINE
  auth: $NETLIFY_AUTH
  edge: true # opt in to dpl v2
  on:
    all_branches: true

after_deploy:
  - netlify deploy --prod

branches:
  only:
    - netlify-villa-clementine
