language: node_js
node_js:
  - "13.1.0"

cache: yarn

install:
  - yarn global add lerna jest now
  - lerna bootstrap

matrix:
  include:
    - name: villa-clementine Pipeline
      env: PACKAGE_LOCATION=packages/villa-clementine PACKAGE_NAME=cbeyondvr-monorepo

cache:
  yarn: true
  directories:
    - node_modules/
    - $PACKAGE_LOCATION/.cache

before_deploy:
  - cd packages/ui-kit
  - yarn build
  - cd ../../$PACKAGE_LOCATION
  - yarn build

# script: now --token=$NOW_TOKEN --target staging
deploy:
  provider: netlify
  site: $NETLIFY_VILLA_CLEMENTINE
  auth: $NETLIFY_AUTH
  edge: true # opt in to dpl v2
  on:
    all_branches: true

branches:
  only:
    - netlify-villa-clementine
