language: node_js
node_js:
  - "12.13.1"

install:
  - yarn global add lerna jest now
  - lerna bootstrap

matrix:
  include:
    - name: dmgdesign Pipeline
      env: PACKAGE_LOCATION=packages/dmgdesign PACKAGE_NAME=cbeyondvr-monorepo DEPLOY_MOVE_TO=.netlify/build

cache:
  yarn: true

before_deploy:
  - cd packages/ui-kit
  - yarn build
  - cd ../../$PACKAGE_LOCATION
  - yarn build

#deploy to netlify
deploy:
  provider: netlify
  site: $NETLIFY_DMGDESIGN
  auth: $NETLIFY_AUTH
  prod: true
  edge: true # opt in to dpl v2
  on:
    all_branches: true

branches:
  only:
    - netlify-dmgdesign
