language: node_js
node_js:
  - "10.15.3"

cache: yarn

install:
  - yarn global add lerna jest now
  - lerna bootstrap

matrix:
  include:
    - name: dmgdesign Pipeline
      env: PACKAGE_LOCATION=packages/dmgdesign PACKAGE_NAME=cbeyondvr-monorepo DEPLOY_TO=dmgdesignsf
    # - name: site-starter Pipeline
    #   env: PACKAGE_LOCATION=packages/site-starter PACKAGE_NAME=cbeyondvr-monorepo  DEPLOY_TO=cbeyond-starter

script:
  - cd $PACKAGE_LOCATION
  - yarn build
#  - yarn test

deploy:
  provider: script
  script: now --token=$NOW_TOKEN --target staging
  skip_cleanup: true
  app: $PACKAGE_NAME
  on:
    all_branches: true
