# note: requires SECRET_NOW_TOKEN env variable to be set by the workflow
name: 'Lerna Package to Netlify'
description: 'Build and Deploy a lerna package to Netlfiy'
author: 'armelle@cbebondvr.com'
inputs:
  PACKAGE_LOCATION:
    description: 'packages/<pkg name>'
    default: 'packages/site-starter'
    required: true
  PACKAGE_NAME:
    description: 'netlify registered application name'
    default: 'cbeyondvr-monorepo'
  # DEPLOY_MOVE_TO:
  #   description: 'netlify expected output directory'
  #   default: '.netlify/build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.PACKAGE_LOCATION }}
    - ${{ inputs.PACKAGE_NAME }}
    # - ${{ inputs.DEPLOY_MOVE_TO }}
