# This is a basic workflow to help you get started with Actions

name: lerna2now

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]
env:
  SECRET_NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  couroubledesign:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: ./.github/actions/lerna2now
      with:
        PACKAGE_LOCATION: packages/couroubledesign
        DEPLOY_TO: couroubledesign
  dmgdesign:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: ./.github/actions/lerna2now
      with:
        PACKAGE_LOCATION: packages/dmgdesign
        DEPLOY_TO: dmgdesignsf
  villa-clementine:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: ./.github/actions/lerna2now
      with:
        PACKAGE_LOCATION: packages/villa-clementine
        DEPLOY_TO: villa-clementine

